labels:
  - "dokujo"
  - "it"
  - "sports"
  - "kaden"
  - "homme"
  - "movie"
  - "peachy"
  - "smax"
  - "topic-news"
model_path: "./engine/news_model"
pretrained_model_name: "cl-tohoku/bert-base-japanese-whole-word-masking"
